"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import Hreader from "./components/hreader";
import Footer from "./components/footer";
import Providers from "./components/providers";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <div className="flex flex-col w-screen h-screen">
          <Hreader />
          <Providers>
            <div className="grow">{children}</div>
          </Providers>
          <Footer />
        </div>
      </body>
    </html>
  );
}
