import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Hreader from "./components/hreader";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <div className="flex flex-col w-screen h-screen">
          <Hreader />
          <div className="grow">
          {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
