import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Hreader from "./hreader";
import Footer from "./footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body className={inter.className}>
        <>
          <Hreader />
          {children}
          <Footer />
        </>
      </body>
    </html>
  );
}
